/**:
  ros__parameters:
    max_agents: 10
    max_velocity: 3.0
    neighbor_validity_ms: 3000
    max_obstacles: 10
    robot_safe_distance: 6.0
    robot_avoidance_gain: 1.0
    obstacles_safe_distance: 1.0
    obstacle_avoidance_gain: 1.0
    clf_enabled: true
    verbose: true
    gui: true
    formation_type: 1
    formation_radius: 15.0
    formation_clf_gain: 1.0
    target_radius: 35.0
    target_period: 180.0
    x_obstacles: [-1000.0]
    y_obstacles: [-1000.0]
    z_obstacles: [3.0]
    team_sizes: [3]
    team_ids  : [1, 2, 3] #put actual drone numbers here
    team_phases: [0]
    x_segment: [-15.0, 15.0]
    y_segment: [0.0, 0.0]
    z_segment: [5.0, 5.0]
